// Objective-C API for talking to example.com/golang-crash-test/crash Go package.
//   gobind -lang=objc example.com/golang-crash-test/crash
//
// File is generated by gobind. Do not edit.

#ifndef __Crash_H__
#define __Crash_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void CrashTest2(void);

#endif
