
// Objective-C API for talking to the following Go packages
//
//	example.com/golang-crash-test/crash
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Golang_crash_test1_FRAMEWORK_H__
#define __Golang_crash_test1_FRAMEWORK_H__

#include "Crash.objc.h"
#include "Universe.objc.h"

#endif
